# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://success-sprint.org
title: Success Sprint
email: contact@success-sprint.org
author: SuccessSprint Inc
description: > # "Write an awesome description for your new site here. 
  Success Sprint: Learning at the Speed of Life
copyright: 'Copyright &copy; 2023 SuccessSprint Inc. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: youtube
    url: https://www.youtube.com/@Success_Sprint
  - title: github
    url: https://github.com/SuccessSprint
  - title: linkedin
    url: https://www.linkedin.com/company/successsprint
